### ISSUE TITLE
How will people contact us?

### ISSUE THREAD

**Issue by dllh** [dllh/kcs-tracing.org#19]
Decide what we want to do about people who wish to contact us. We could make a "contact us" form (one already exists in fact, but is hidden), but it might take some doing to get mail working on this server (which also introduces one more technology dependency to the chain we're already using). Maybe a gmail address we set up for this would be better and simpler?

**Comment by HeatherHMorgan** [comment]
I created a new gmail account - KCSDashboard@gmail.com. I'll email the password to you.

**Comment by HeatherHMorgan** [comment]
Just emailed you the password!

**Comment by dllh** [comment]
Cool, thanks! Added the email to the main nav and the privacy page in 39acbd2. Closing this one out.
