### ISSUE TITLE
Get a different domain name?

### ISSUE THREAD

**Issue by dllh** [dllh/kcs-tracing.org#22]
I had been thinking of this chiefly as a contact tracing app, with some data available too. As H mentioned elsewhere (edits to the "privacy" page, I think?), we're not really calling it contact tracing at this point, so the domain kcs-tracing.org may be a misnomer. Would we like to get a new domain and host the site from there instead? If so, what domain makes sense?

**Comment by HeatherHMorgan** [comment]
I was thinking the same thing, actually. How about KCSdashboard.org?

**Comment by dllh** [comment]
Cool, I've registered that and will point it to the site later today.

**Comment by HeatherHMorgan** [comment]
Awesome! Thanks!

I am happy to chip in to help pay for some of the expenses you are incurring.

Also, for the KCS-Tracing site (if it's already paid for), do you want to point it to this - https://docs.google.com/spreadsheets/d/1oS1f7F2Xz_mMGINZEP0Nwf_emi6NTcnIXg-ATXs-q1w/edit#gid=935460680

If you have something else already in mind, please disregard! Just a thought!

Thanks!
Heather

**Comment by dllh** [comment]
The new domain is all set up and pointing to the site. And the old domain is now pointing over to the Google doc. One little thing is that you and I might wind up seeing security errors, as the https url (vs. the http) is likely stored in our browsers, and GoDaddy's redirection service doesn't seem to deal with https cleanly. For most in the future, it shouldn't be a problem, as they won't have the https domain cached in their browser. We should wait a little while (a few hours at least) before sharing the domain, as DNS propagation can take a little bit and we might have "it doesn't work for me" reports.

The expenses are either minimal or are things I was already paying for, but I appreciate the offer. If my little server turns out not to be robust enough for the app, we may need to upgrade that a bit to accommodate more traffic, but honestly I think it'll be ok unless we have some big spike event or something.
