### ISSUE TITLE
No chart displays for a school if the report is filed for a date prior to the last thirty days

### ISSUE THREAD

**Issue by HeatherHMorgan** [dllh/kcs-tracing.org#24]
I created a report for Austin-East 10th grader with symptom onset of 8/1 and positive test of 8/4. When I checked the chart for Austin East, nothing showed up, and the message said: 
![image](https://user-images.githubusercontent.com/90143051/132281611-789d67fe-602c-4ad9-91d4-447a21c3fcfd.png)

There is no mention of the 30-day window in this situation which may leave a user confused. (I, of course, know that we are only displaying the last 30 days, and that's why no data is displaying.) Is it easy to change the language to make it clear that the reason nothing is showing is because there have been no new active cases for the last thirty days?

**Comment by dllh** [comment]
Great catch! I've shipped a little fix that adds some clarity.
