### ISSUE TITLE
Top box on main page - 30 day count

### ISSUE THREAD

**Issue by HeatherHMorgan** [dllh/kcs-tracing.org#30]
Health officials typically use a 10-day period or a 14-day period determine whether a case is active. In addition to the 30-day box, could we include 10 day and 14 day figures as well?

**Comment by dllh** [comment]
Yep, should be pretty easy to add those two boxes alongside the one that's already there.

**Comment by dllh** [comment]
Alrighty, I've added 10- and 14-day boxes now too.

**Comment by HeatherHMorgan** [comment]
Awesome thanks! I can't remember if I told you but I can see all the menu
options on mobile now as of this morning!
