### ISSUE TITLE
Add message to report form re: obtaining an access code / generate new access codes

### ISSUE THREAD

**Issue by HeatherHMorgan** [dllh/kcs-tracing.org#31]
If someone wants to create a report but doesn't have an access code, we need to let them know how to get one. On the report form near the access code box, can we add a message that says "To obtain an access code, please contact the admin of your school's DIY Contact Tracing Group or send an email to kcsdashboard@gmail.com?" Let's go ahead and create more one-time use codes as well. I will "issue" 5 - 10 codes to each of the DIY admins to provide to members in their groups who need them.

Thanks!
Heather

**Comment by dllh** [comment]
Ah, good call. I've added some info to the little hint text under the field:

![Screen Shot 2021-09-08 at 12 33 53 PM](https://user-images.githubusercontent.com/2738252/132549109-23c0723f-4cf3-4bc3-8d76-2a34cc39fc25.png)
